project_id = "ephpobvbzlemgixverve"

[functions.batch-call]
verify_jwt = false

[functions.campaign-batch-list]
verify_jwt = false

[functions.campaign-batch-detail]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[functions.process-retry-calls]
verify_jwt = false