project_id = "ephpobvbzlemgixverve"

[functions.batch-call]
verify_jwt = false

[functions.billplz-integration]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.manual-upgrade]
verify_jwt = false

[functions.process-retry-calls]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false